---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "traefik.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "traefik.name" . }}
    helm.sh/chart: {{ template "traefik.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    metallb.universe.tf/address-pool: public-{{ .Values.region | lower }}
  {{- if .Values.externalDns.enabled }}
    external-dns.alpha.kubernetes.io/hostname: {{ (include "traefik.externalHostName" .)  | trim | squote | quote }}
  {{- end }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: {{ template "traefik.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.ports.web.exposed }}
      name: web
      targetPort: "web"
      protocol: TCP
    - port: {{ .Values.ports.websecure.exposed }}
      name: websecure
      targetPort: "websecure"
      protocol: TCP
    {{ if .Values.dashboard.enabled }}
    - port: {{ .Values.ports.traefik.exposed }}
      name: traefik
      targetPort: "traefik"
      protocol: TCP 
    {{ end }}
  
